#!/bin/sh
# deploy_vps.sh — set up a central VPS as the home of a shared Brain vault.
#
# It wires up three pieces of housekeeping so a team can share one vault safely:
#   1. A 15-minute cron job that auto-commits any vault changes to git.
#   2. A daily tar backup with rotation (keeps the last N archives).
#   3. A read-only git mirror (a bare repo) that clients clone/pull from.
#
# Everything is idempotent: re-running it re-applies the same state without
# creating duplicates. All host-specific values are placeholders you override
# with environment variables — no real paths, repos, or hosts are baked in.
#
# Usage:
#   BRAIN_VAULT_PATH=/srv/brain/vault \
#   BRAIN_MIRROR_PATH=/srv/brain/vault.git \
#   BRAIN_BACKUP_DIR=/srv/brain/backups \
#   BRAIN_REMOTE_URL=git@git.example.com:team/brain-vault.git \
#   ./scripts/deploy_vps.sh
#
# Optional env:
#   BRAIN_BACKUP_KEEP   number of daily archives to retain (default: 14)
#   BRAIN_GIT_NAME      commit author name for auto-commits (default: brain-bot)
#   BRAIN_GIT_EMAIL     commit author email        (default: brain-bot@example.com)
#   CRON_USER           user whose crontab is edited (default: current user)
set -e

# ---- config (all overridable; safe placeholder defaults) --------------------
VAULT="${BRAIN_VAULT_PATH:-/srv/brain/vault}"
MIRROR="${BRAIN_MIRROR_PATH:-/srv/brain/vault.git}"
BACKUP_DIR="${BRAIN_BACKUP_DIR:-/srv/brain/backups}"
REMOTE_URL="${BRAIN_REMOTE_URL:-}"            # optional upstream to push mirror to
BACKUP_KEEP="${BRAIN_BACKUP_KEEP:-14}"
GIT_NAME="${BRAIN_GIT_NAME:-brain-bot}"
GIT_EMAIL="${BRAIN_GIT_EMAIL:-brain-bot@example.com}"
CRON_USER="${CRON_USER:-$(id -un)}"

# Where we drop the generated helper scripts (kept next to the vault).
HELPER_DIR="$(dirname "$VAULT")/brain-ops"

echo "==> Brain OS VPS setup"
echo "    vault      : $VAULT"
echo "    mirror     : $MIRROR"
echo "    backups    : $BACKUP_DIR (keep $BACKUP_KEEP)"
echo "    helpers    : $HELPER_DIR"

[ -d "$VAULT" ] || { echo "ERROR: vault directory does not exist: $VAULT"; exit 1; }
mkdir -p "$BACKUP_DIR" "$HELPER_DIR"

# ---- 1. make sure the vault is a git repo -----------------------------------
if [ ! -d "$VAULT/.git" ]; then
    echo "==> initialising git repo in vault"
    git -C "$VAULT" init -q
    git -C "$VAULT" config user.name  "$GIT_NAME"
    git -C "$VAULT" config user.email "$GIT_EMAIL"
    git -C "$VAULT" add -A
    git -C "$VAULT" commit -q -m "Initial vault snapshot" || true
else
    echo "==> vault already under git"
fi

# ---- 2. read-only mirror clients pull from ----------------------------------
# A bare repo serves as the distribution point. Clients get read-only access to
# it (e.g. behind an SSH command restriction or an HTTP git server); the VPS is
# the single writer, matching the "single writer" boundary in ARCHITECTURE.md.
if [ ! -d "$MIRROR" ]; then
    echo "==> creating bare mirror repo"
    git init -q --bare "$MIRROR"
fi
if ! git -C "$VAULT" remote | grep -qx mirror; then
    git -C "$VAULT" remote add mirror "$MIRROR"
fi
# Optional upstream (e.g. a hosted git service) clients can pull from instead.
if [ -n "$REMOTE_URL" ]; then
    if ! git -C "$VAULT" remote | grep -qx origin; then
        git -C "$VAULT" remote add origin "$REMOTE_URL"
    else
        git -C "$VAULT" remote set-url origin "$REMOTE_URL"
    fi
fi

# ---- 3. auto-commit helper (invoked by cron every 15 min) -------------------
AUTOCOMMIT="$HELPER_DIR/autocommit.sh"
echo "==> writing $AUTOCOMMIT"
cat > "$AUTOCOMMIT" <<EOF
#!/bin/sh
# Auto-commit any vault changes and push to the read-only mirror.
# Generated by deploy_vps.sh — safe to re-generate.
set -e
VAULT="$VAULT"
git -C "\$VAULT" config user.name  "$GIT_NAME"
git -C "\$VAULT" config user.email "$GIT_EMAIL"
# Nothing staged and nothing changed? exit quietly.
if [ -z "\$(git -C "\$VAULT" status --porcelain)" ]; then
    exit 0
fi
git -C "\$VAULT" add -A
git -C "\$VAULT" commit -q -m "auto: vault snapshot \$(date -u +%Y-%m-%dT%H:%M:%SZ)"
# Publish to the local bare mirror; push to upstream too if configured.
git -C "\$VAULT" push -q mirror HEAD:refs/heads/main || true
if git -C "\$VAULT" remote | grep -qx origin; then
    git -C "\$VAULT" push -q origin HEAD:refs/heads/main || true
fi
EOF
chmod +x "$AUTOCOMMIT"

# ---- 4. daily backup helper (invoked by cron once a day) --------------------
BACKUP="$HELPER_DIR/backup.sh"
echo "==> writing $BACKUP"
cat > "$BACKUP" <<EOF
#!/bin/sh
# Daily tar backup of the vault with rotation.
# Generated by deploy_vps.sh — safe to re-generate.
set -e
VAULT="$VAULT"
BACKUP_DIR="$BACKUP_DIR"
KEEP="$BACKUP_KEEP"
STAMP="\$(date -u +%Y%m%d)"
ARCHIVE="\$BACKUP_DIR/brain-vault-\$STAMP.tar.gz"
# Exclude the disposable runtime and git internals from the archive.
tar -czf "\$ARCHIVE" \\
    --exclude='.git' \\
    --exclude='.brain-runtime' \\
    -C "\$(dirname "\$VAULT")" "\$(basename "\$VAULT")"
# Rotation: keep only the most recent \$KEEP archives.
ls -1t "\$BACKUP_DIR"/brain-vault-*.tar.gz 2>/dev/null \\
    | tail -n +\$((KEEP + 1)) \\
    | while read -r old; do rm -f "\$old"; done
EOF
chmod +x "$BACKUP"

# ---- 5. install cron entries (idempotent) -----------------------------------
# We tag our lines with a marker comment so re-runs replace them cleanly rather
# than piling up duplicates.
MARKER="# brain-os-managed"
echo "==> installing cron entries for user $CRON_USER"
CRON_TMP="$(mktemp)"
# Preserve any existing crontab minus our previously-managed lines.
crontab -u "$CRON_USER" -l 2>/dev/null | grep -v "$MARKER" > "$CRON_TMP" || true
{
    echo "*/15 * * * * $AUTOCOMMIT >/dev/null 2>&1 $MARKER"
    echo "17 3 * * * $BACKUP >/dev/null 2>&1 $MARKER"
} >> "$CRON_TMP"
crontab -u "$CRON_USER" "$CRON_TMP"
rm -f "$CRON_TMP"

echo "==> done."
echo "    Clients pull the vault (read-only) with, e.g.:"
echo "      git clone $MIRROR my-brain"
echo "    Auto-commit runs every 15 min; backups land in $BACKUP_DIR (keep $BACKUP_KEEP)."
